version: "2"
run:
  allow-parallel-runners: true
linters:
  enable:
    - unused
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
