l1:

observability:

l2:
  l1-chain-id: 0
  l1-el-url: http://127.0.0.1:8080
  l1-cl-url: http://127.0.0.1:9090
  coordinator-private-key: YOUR_COORDINATOR_PRIVATE_KEY_HERE
  wallet:
    private-key: YOUR_PRIVATE_KEY_HERE
    address: YOUR_ADDRESS_HERE
  chain-ids:
    rollup-a: 77777
    rollup-b: 88888
  deployment-target: live  # "live" or "calldata"
  genesis-balance-wei: "100000000000000000"  # 0.1 ETH for funded accounts
  repositories:
    op-geth:
      url: https://github.com/ssvlabs/op-geth.git
      branch: stage
    optimism:
      url: https://github.com/ethereum-optimism/optimism.git
      branch: op-node/v1.13.6
    publisher:
      url: git@github.com:ssvlabs/rollup-shared-publisher.git
      branch: stage