ARG OP_RBUILDER_IMAGE_TAG=latest

FROM ghcr.io/flashbots/op-rbuilder:${OP_RBUILDER_IMAGE_TAG} AS base

FROM debian:bookworm-slim
RUN apt-get update \
    && apt-get install -y --no-install-recommends ca-certificates zlib1g \
    && rm -rf /var/lib/apt/lists/*

COPY --from=base /app/rbuilder /app/rbuilder

ENTRYPOINT ["/app/rbuilder"]
